#!/bin/sh

# Set these paths appropriately

BIN=/home/kroggel/Arbeitsfläche/TreeTagger/bin
CMD=/home/kroggel/Arbeitsfläche/TreeTagger/cmd
LIB=/home/kroggel/Arbeitsfläche/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
